version: '3'

services:
  redis:
    image: redis:2.8
  db:
    image: postgres
  backend:
    build: ./backend
    command: bash docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - .:/code2
    ports:
      - "3000:3000"
    depends_on:
      - backend